<a href="https://colab.research.google.com/github/shirataki-takipon/image_classification_traning/blob/master/test_process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
sys.path.append('/content/drive/My Drive/image_classification_traning')
import ic_module as ic
import os.path as op

In [2]:
while True:
    while True:
        imgname = input("\n>> 入力したい画像ファイル(「END」で終了) ： ")
        if op.isfile(imgname) or imgname == "END":
            break
        print(">> そのファイルは存在しません！")
    if imgname == "END":
        break

    # 関数実行
    ic.TestProcess(imgname)


>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/image_classification_traning/original_data/test_image/000002.jpg
>> 計算結果↓
[[8.6751446e-05 9.9970180e-01 2.1145448e-04]]
>> この画像は「松岡茉優」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/image_classification_traning/original_data/test_image/000005.jpg
>> 計算結果↓
[[9.8596710e-01 1.4024942e-02 7.9689289e-06]]
>> この画像は「堀北真希」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/image_classification_traning/original_data/test_image/000008.jpg
>> 計算結果↓
[[9.9803180e-01 1.9203854e-03 4.7839614e-05]]
>> この画像は「堀北真希」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/image_classification_traning/original_data/test_image/000015 (1).jpg
>> 計算結果↓
[[9.7750163e-01 3.0323719e-05 2.2468047e-02]]
>> この画像は「堀北真希」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/image_classification_traning/original_data/test_image/000015.jpg
>> 計算結果↓
[[9.9190170e-01 8.0279307e-03 7.0378155e-05]]
>> この画像は「堀北真希」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My 